export const SHOW_MODAL = 'SHOW_MODAL';
export const SELECTED_ROW_DATA = 'SELECTED_ROW_DATA';
export const AFTER_MERGE_SAVE = 'AFTER_MERGE_SAVE';
export const GLOBAL_RESPONSE = 'GLOBAL_RESPONSE';
export const FETCH_TABLE_DATA = 'FETCH_TABLE_DATA';
export const FETCH_TABLE_DATA_PERCENTAGE = 'FETCH_TABLE_DATA_PERCENTAGE';
export const INITIAL_TRANSACTION = 'INITIAL_TRANSACTION';
export const CURRENT_VERSION = 'CURRENT_VERSION';
